apiVersion: v1
kind: Service
metadata:
  name: liquidwar-play
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: liquidwar-play
spec:
  selector:
    app.kubernetes.io/name: liquidwar-play
  ports:
    - name: http
      port: 8080
      targetPort: 8080
